# I have applied for twitter app keys.
# My keys are not yet generated by twitter
# as soon as application gets approved I will add keys here


def oauth():
    return {
        "consumer_key" : "",
        "consumer_secret": "",
        "token_key":"",
        "token_secret":""
    }
